# For more information see: https://github.com/actions/setup-java#apache-maven-with-a-settings-path

name: Build

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2

            -   name: Set up Java 16
                uses: actions/setup-java@v2
                with:
                    distribution: 'temurin'
                    java-version: '16'

            -   name: Build with Maven
                run: mvn -B package --file pom.xml