# For more information see: https://github.com/actions/setup-java#apache-maven-with-a-settings-path

name: Test

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]
    workflow_dispatch:

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2

            -   name: Set up Java 16
                uses: actions/setup-java@v2
                with:
                    distribution: 'temurin'
                    java-version: '16'
                    cache: maven

            -   name: Test with Maven
                run: mvn -B test --file pom.xml

            -   name: Publish Unit Test Results
                uses: EnricoMi/publish-unit-test-result-action@v1
                if: always()
                with:
                    files: test-results/**/*.xml